spring:
  rabbitmq:
    host: 192.168.40.129
    port: 5672
    username: admin
    password: admin
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000ms

  application:
    name: rabbitMQ-consumer

server:
  port: 8090